### ISSUE TITLE
Not installable via luarocks

### ISSUE THREAD

**Issue by flintinatux** [Alloyed/loverocks#14]
Not sure what's up, because I can find it at https://luarocks.org/modules/alloyed/loverocks, but it's not installable:

```
$ luarocks install loverocks

Error: No results matching query were found.
```

I'm able to install all sorts of other rocks, just not this one.

**Comment by Alloyed** [comment]
If I had to guess, the copy of luarocks you're using is hosted on an incompatible version of lua.
you can check like so:
```
$ luarocks --help | grep "Lua version"
	Lua version: 5.1
```
5.1 is correct, 5.2/5.3 aren't.

Side note: I also think you might be using an out-of-date version of luarocks, because that particular error message has been made more informative in recent versions. If you got it from a package manager, you might want to check out [hererocks](https://github.com/mpeterv/hererocks) instead, which tracks upstream pretty closely.

**Comment by flintinatux** [comment]
Ah, you are correct.  I'm on Lua 5.2, which I need for another library.  Next time I'll know to check the rockspec.  For now, I guess I'll just stick with the copy/paste method for deps.  In the meantime, I'll also checkout `hererocks`.  Thanks for the tip!
