### ISSUE TITLE
increasing the lua version upper bound

### ISSUE THREAD

**Issue by AKST** [Alloyed/loverocks#8]
Is this library compatible with later versions of lua, like 5.2/5.3, if so I was wondering if it's possible to increase the lua upper version bound, [as I'm having trouble installing the correct version of loverocks through luarocks][my issue], due to my system lua being version 5.3. 

I'm kind of noob with lua & love, so if there's a valid reason for this version constraint like needing to remove deprecated apis, etc, I'd be willing to help where I can.

Cheers

[my issue]: https://github.com/keplerproject/luarocks/issues/601#issuecomment-240202711

**Comment by Positive07** [comment]
LÖVE uses Lua 5.1 (LuaJIT), when LuaRocks uses another Lua version, Loverocks mixes all up and will only let you install libraries that work with the LuaRocks Lua version (in your case that would be 5.3), when LÖVE is using something different and may not be compatible with the libraries you can use in 5.3

Check [this](https://github.com/Alloyed/loverocks/issues/1#issuecomment-109860735) comment from @Alloyed at issue #1, and also [this](https://github.com/Alloyed/loverocks/issues/2#issuecomment-161695557) comment at #2

For reference the change was introduced at 2fd963a5, [here](https://github.com/Alloyed/loverocks/commit/2fd963a5412a6989afa42c901c1ec753302f02d5#diff-aaac408fc3827c4b19ae6538f885dd6cR13)

The problem is in LuaRocks which is not designed for any kind of setup that uses more than one Lua version

**Comment by AKST** [comment]
Okay thanks, I might install a older version of lua and rebuild luarocks. That said it might be worth adding a more obvious note on the repo about this requirement.

**Comment by Positive07** [comment]
Well users of Github should also get used to check if the problem they are reporting has already been reported or is actually a fix for other issue, as you already saw it wasn't hard to find why this decision was made, only by looking at the first two issues, just saying.

Cheers

**Comment by AKST** [comment]
Eh, a simple note in the installation section would be sufficient. Either way it's a seperate issue so I'll open a seperate issue. Thanks again for pointing why loverocks uses 5.1
