### ISSUE TITLE
Improving the getting started story for new users

### ISSUE THREAD

**Issue by AKST** [Alloyed/loverocks#9]
I'm just wondering if it might be putting a warning in the installation section that the latest version of `loverocks` won't install unless you're using lua version `5.1`, and if you're using a later version of lua (like version `5.3`) you'll end up with loverocks version `0.2.0`. Like as a new users it's not really something you expect, and before I figured out I went though a bit of a wild goose chase.

**Comment by Alloyed** [comment]
Thanks for reporting! This is exactly the sort of thing I would never have thought to test myself, so it really helps.

So I found a flag in the luarocks.org website that removes the older, broken versions from being installed. Now this is what happens when I try to install loverocks using lua 5.2:
```
$ luarocks-5.2 install loverocks --local

Error: No results matching query were found.
```

This isn't necessarily less cryptic but in newer versions of luarocks it should get better:(https://github.com/keplerproject/luarocks/pull/524)

Getting a luarocks host at all seems to be a common issue, so I think I'll add an extra section that just describes how to do that from the common OS package managers and so on.

**Comment by AKST** [comment]
Awesome I think this will be a much better experience for new users, as they won't go through the whole experience of having to figure out they installed the wrong version. Thanks 😄
